### ISSUE TITLE
No C# 7 support

### ISSUE THREAD

**Issue by MartinOSchmidt** [oleg-shilo/scripts.npp#5]
Thanks for this nice plugin!

However I wonder why "Automation Scripts" would not compile C# 6 or 7 syntax (e.g. expression-bodied property class-members like `public string FullName => $"{FirstName} {LastName}";`) while the "cs-script.npp"-plugin gladly does.

I.e. if I build the same script once with "scripts.npp" the other time with "cs-script.npp" the first fails the later succeeds.

Can I configure somewhere the C# language version to use?

**Comment by oleg-shilo** [comment]
Unfortunately it's problematic. 
You see, I have stopped investing in this very project due to the lower than expected popularity so extending it with Roslyn (C# 7) is a high effort low value exercise that I cannot commit to due to my commitments in other open Source projects.

Sorry I know it's not the answer you were hoping for.

Though I will gladly incorporate the changes to the deployment (e.g. include Roslyn) should someone contribute this work

**Comment by MartinOSchmidt** [comment]
OK. I see.
I just was/am confused, why "Automation Scripts" would not compile C# 6, while, cs-script.npp does, where both use CSScriptLibrary ("Automation Scripts" seems to use even a newer version).
Is not all the compiling stuff done inside this library?

But of course I understand if you do not want/can invest any more time in this. And I am not the right guy for this, as I do not have experience with Roslyn as such.

Still it would be nice to understand where the problem is :)

**Comment by oleg-shilo** [comment]
I understand your confusion. 
CSScriptLibrary is not a compiler nor interpreter. It is a facilitator of the on-fly C# compilation that is to be done by .NET compilers not CS-Script.

Starting from 2015 MS stopped shipping the latest C# compiler (Roslyn) with .NET installations but still continued shipping compilers for C#5. That's why you can always compile for C#5.

"Automation Scripts" plugin (`scripts.npp`) is a simple library that is not to be used fro an incentive scripting but for automating N++. Thus it was OK to leave it with this limitation.

"CS-Script" plugin (`cs-script.npp`) is a general purpose comprehensive scripting system and having supporting the latest C# syntax is essential in this case. Thus the plugin was reworked to include Roslyn compiler since .NET does not include it. Thus in turn increased the size of the plugin by 25M+ and complicated the whole deployment and the runtime behavier. But it was an adequate price for the improved functionality (latest C# syntax).

Thus "Automation Scripts" can undergo the same improvement but it is hard to justify such an effort unless there is a user demand for this.

Please be aware that .NET 5 version of CS-Script has been released and I am slowly porting all plugins and extensions so they can support it. N++ is not ported yet. VSCode and Sublime are.and .NET 5 does include latest compilers (yey!) that's why it is so beneficial for CS-Script to be integrated with this version of .NET.

However porting "Automation Scripts" on .NET5 is problematic as it is essentially a .NET Core. And .NET Core binaries are not yet supported N++.

**Comment by MartinOSchmidt** [comment]
Thanks oleg for the explanation. While I was aware that the actual compilation is done by the compiler(s) and not by CSScriptLibrary itself, I was not aware that the work/problems are due to the (missing) deployment of Roslyn with .NET (4). Good to know! :)

Thanks again ... and one additional question, I hope you don't mind I ask it here: I saw that within the cs-script.npp-plugin there is also the available the ScintillaGateway (via Kbg.NppPluginNET.PluginInfrastructure.ScintillaGateway). Is there a way  to subscribe to the Notepad/Scintilla notifications, so one could do similar things like with the "Automation Scripts" NppScript.OnNotification event?

**Comment by oleg-shilo** [comment]
The problem is that cs-script.npp-plugin runs scripts outside of npp process. Exactly the same way you would do it from command prompt. Thus the script cannot access the running  instance of npp.

Whereas "Automations Scripts" plugin is running in the npp process that's why it can automate the editor.

Anyway, I will be revisiting all my plugins and extensions when  porting them on .NET 5. I will have a look at extending "Automations Scripts" plugin with Roslyn. I cannot promise but will try. This way you will get your C# 6+ syntax

**Comment by MartinOSchmidt** [comment]
Thanks. That ist great! Looking forward to.
